---
resources:
  - name: repo
    type: git
    icon: github
    source:
      uri: git@github.com:awolde/sql-automate.git
      branch: main
      private_key: ((gcp.SSH_KEY))
      git_config:
        - name: core.sshCommand
          value: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

jobs:
  - name: restore-job
    plan:
      - get: repo
        trigger: true
      - task: init-plan
        config:
          params:
            GOOGLE_OAUTH_ACCESS_TOKEN: ((gcp.GOOGLE_OAUTH_ACCESS_TOKEN))
            BUCKET: ((gcp.BUCKET))
            PREFIX: ((gcp.PREFIX))
            TF_VAR_project: ((gcp.PROJECT))
            TF_VAR_vpc_project: ((gcp.PROJECT))
            TF_VAR_db_user: ((gcp.DB_USER))
            TF_VAR_db_user_pass: ((gcp.DB_PASSWORD))
            TF_VAR_bucket: ((gcp.BUCKET))
            ENV: test
          inputs:
            - name: repo
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: hashicorp/terraform
              tag: latest
          outputs:
            - name: plan-output
          run:
            path: sh
            args:
              - -exc
              - |
                cd repo/
                cp ${ENV}.tfvars terraform.tfvars
                terraform init -backend-config="bucket=${BUCKET}" -backend-config="prefix=${PREFIX}/${ENV}" && terraform plan -out=../plan-output/plan.out
                cp -r .terraform ../plan-output/
                cp .terraform.lock.hcl ../plan-output/
                #cp main.tf plan-output/

      - task: apply
        config:
          platform: linux
          params:
            GOOGLE_OAUTH_ACCESS_TOKEN: ((gcp.GOOGLE_OAUTH_ACCESS_TOKEN))
          image_resource:
            type: registry-image
            source:
              repository: hashicorp/terraform
              tag: latest
          inputs:
            - name: plan-output
          outputs:
            - name: state-file
          run:
            path: sh
            args:
              - -exc
              - |
                cd plan-output
                terraform apply plan.out