---
- name: setup webserver
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: httpd installed
      ansible.builtin.yum:
        name: httpd
        state: latest
    - name: custom index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
                   Lab Custom Web Page
    - name: httpd service enabled
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started
    - name: open firewall
      ansible.posix.firewalld:
        service: http
        state: enabled
        immediate: true
        permanent: true
        
##https://codingbee.net/ansible/ansible-a-playbook-for-setting-up-an-apache-webserver
